# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: copy-configs
        name: copy-configs
        description: copying config files  
        entry: ./copy-configs.sh
        language: script  
